### ISSUE TITLE
Expanded documentation

### ISSUE THREAD

**Issue by brandondube** [MREYE-LUMC/ZOSPy#35]
This issue is part of my JOSS review, https://github.com/openjournals/joss-reviews/issues/5756

Copying verbatim, the grading criteria are:

### Documentation

- [ ] **A statement of need**: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Most of these do exist.  And the docstrings are even quite good, with the few I went looking for in the source code replete with examples!  However, this is a large software package, and when a user visits its website (the Github repo is all that exists for this, as best I can tell), perhaps just 5% or something like that of it "is documented" in the README.

I think it would be a great enhancement if a documentation site was set up for your package, for example using sphinx and hosted on readthedocs.  Or really whatever you like, but sphinx and the `nbsphinx` extension allow you to make quite delightful documentation with jupyter notebooks.

**Comment by LucVV** [comment]
Thank you for the feedback, we will look into this and get back to you!

**Comment by LucVV** [comment]
Hi @brandondube, we have addressed this feedback by hosting the documentation on [readthedocs](https://zospy.readthedocs.io/en/latest/ ) as suggested.
